strategy: MovingAverageCrossStrategy
cash: 150000.00
symbols:
  - SPX Index         # list
root_multiplier:
benchmark: SPX Index           # compare ti buy and hold, or leave it empty
start_date: 2016-01-01
end_date: 2017-05-01
params:
  short_window: 10      # dict
  long_window: 20
datasource: local   # local, quandl, tushare
hist_dir: d:/workspace/elitequant_python/hist/
output_dir: d:/workspace/elitequant_python/out/
fvp_file:           # FUT_VAL_PT, for example stocks = 1; CLA Comdty is 1000
#---- used by optimization engine ----------#
batch_tag:
params_list:
    - short_window: 10
      long_window: 20
    - short_window: 20
      long_window: 40
    - short_window: 50
      long_window: 100
