strategy: MovingAverageCrossStrategy
cash: 500000.00
tickers:
  - AMZN
  - AAPL
  #- 600000
benchmark:            # or leave it empty
start_date: 2010-01-01
end_date: 2017-05-01
datasource: local   # local, quandl, tushare
hist_dir: d:/workspace/elitequant_python/hist
output_dir: d:/workspace/elitequant_python/out